### ISSUE TITLE
Add API to dynamically manage timeline markers

### ISSUE THREAD

**Issue by protyposis** [bitmovin/bitmovin-player-ui#103]
Currently it is possible to add generic `TimelineMarker` markers to the timeline (i.e. `SeekBar`), but only via the `UIConfig` at construction time of the `UIManager`.

The time line marker interface:
https://github.com/bitmovin/bitmovin-player-ui/blob/d8a6978f593ad229e96f051257b7d518d9687619/src/ts/uimanager.ts#L61-L64

The UI config interface that takes an array of timeline markers:
https://github.com/bitmovin/bitmovin-player-ui/blob/d8a6978f593ad229e96f051257b7d518d9687619/src/ts/uimanager.ts#L66-L78

The constructor that takes the config:
https://github.com/bitmovin/bitmovin-player-ui/blob/d8a6978f593ad229e96f051257b7d518d9687619/src/ts/uimanager.ts#L167

We need an API that allows dynamic management of these markers, i.e. add and remove during the lifetime of the `UIManager`. Additionally we want to be able to define different kinds of markers, e.g. chapter and ad markers that need to look and possibly work differently.

Currently these markers mark points in time. We also want to be able to mark time intervals. While this should be easily achievable to mark intervals of the main content, it is going to be more difficult for inserted ad breaks that modify the timeline, so we may want to handle this in a separate follow-up issue once necessary. The API for this would be quite simple, but the question of how this is rendered on a seek bar is to be discussed (e.g. how do we transform the timeline of the seekbar if an ad interval is inserted? how is the mapping from the seekbar to the content done? how do we even know in advance how long an ad break is going to be?).

**Comment by protyposis** [comment]
Proposed API extension:

```ts
interface TimelineMarker {
  /**
   * Optional CSS class that is applied to the marker and can be used to differentiate 
   * different types of markers by their style (e.g. different color of chapter markers and 
   * ad break markers).
   */
  cssClass?: string;
}

class UIManager {
  /**
   * Returns the list of all added markers in undefined order.
   */
  getMarkers(): TimelineMarker[];
  /**
   * Adds a marker to the timeline. Does not check for duplicates/overlaps at the `time`.
   */
  addMarker(timelineMarker: TimelineMarker): void;
  /**
   * Removes a marker from the timeline (by reference) and returns `true` if the marker has 
   * been part of the timeline and successfully removed, or `false` if the marker could not
   * be found and thus not removed.
   */
  removeMarker(timelineMarker: TimelineMarker): boolean;
}
```

**Comment by protyposis** [comment]
Open questions:
 * Do we want to support these markers on live streams as well? (the markers would have to be animated and move across the timeline as the playhead progresses/changes)
 * Do we want to allow customization of the `SeekBarLabel`? (this label currently displays the time, an optional title text, and a thumbnail if available)
   * Deactivate the label per marker?
   * Allow a custom image instead of the thumbnail?
   * Allow custom content instead of the default content?

**Comment by unki2aut** [comment]
**Notes from architectural meeting 2018-06-19**
* We don't support markers on live streams right now
* Add `cssClasses` property to `TimelineMarker`, the same classes would be propagated to the label
* A `content()` callback which returns a DOM element could be added in the future

**Comment by protyposis** [comment]
API extension updated: https://github.com/bitmovin/bitmovin-player-ui/issues/103#issuecomment-391295236

**Comment by protyposis** [comment]
Renamed method names to include `Timeline` for more consistent naming that matches the object type's name, e.g. `getMarkers` -> `getTimelineMarkers`.

**Comment by protyposis** [comment]
Released in `2.16.0`

**Comment by alexanderte** [comment]
Just a minor issue; is there any place where these API calls are documented? I tried to use the search functionality for [version 7](https://bitmovin.com/docs/player/api-reference/web/web-sdk-api-reference-v7#/player/web/7/docs/index.html) and [version 8](https://bitmovin.com/docs/player/api-reference/web/web-sdk-api-reference-v8#/player/web/8/docs/index.html), but no search results appeared. It shouldn’t be too difficult to figure it out from the code, but I was about to open an issue as I didn’t think this functionality was implemented.

**Comment by protyposis** [comment]
You were searching the player API docs which only contains player API, no UI API. The main documentation of the UI is this repository with the readmne, changelog, source code and issues.

**Comment by alexanderte** [comment]
Ah, okay. I’ve had a bit of a struggle distinguishing the boundaries of the two, but I think I’m starting to get it.
