### ISSUE TITLE
Typescript definitions doesn't work

### ISSUE THREAD

**Issue by 19majkel94** [bitmovin/bitmovin-player-ui#104]
There's some problem with building or publishing this package on npm.

Here is the content of `main.d.ts` file in `node_modules`:
```ts
/// <reference path="../../../src/ts/player.d.ts" />
export {};
```

It results in no typings at all:

![image](https://user-images.githubusercontent.com/10618781/40615612-c782bbda-6287-11e8-962c-7dfa7e2772c2.png)

I've installed latest version `"bitmovin-player-ui": "^2.13.0"`

**Comment by protyposis** [comment]
> Thanks! Now the namespace works, however it would be better to be able to do `import { SourceConfig } from 'bitmovin-player-ui';` I think.

Yes that would be much nicer and will be fixed when we move the definitions from the UI to the player package.

For the second problem, can you please open a new issue with instructions to reproduce?

**Comment by 19majkel94** [comment]
@protyposis  
As I reported, the `main.d.ts` file is invalid, in newest version it even don't have the `export {}` statement so TS throw error `File '(...)/node_modules/bitmovin-player-ui/dist/js/framework/main.d.ts' is not a module.`

I see that in `dist` folder of `bitmovin-player-ui` package downloaded from npm there are many modules definition files, like `uimanager.d.ts`. I would need access to the types defined there, to make `bitmovinPlayerUI.UIManager.Factory.buildDefaultUI(...)` work.

What setup of compliation do you use that it throws away `module.exports = playerui;`? Typescript compiler should easily emit correct type definition from `main.ts` file 😕

**Comment by protyposis** [comment]
Fixed in `develop` / v3.

**Comment by protyposis** [comment]
`3.0.0` released. UI type definitions have been fixed, player type definitions have been removed from the UI package. They can now be found in `bitmovin-player@8`.
