### ISSUE TITLE
[TS] Incorrect DRMConfig type

### ISSUE THREAD

**Issue by 19majkel94** [bitmovin/bitmovin-player-ui#106]
Right now we have empty `DRMConfig` interface:
```ts
interface DRMConfig {
}
```
which is extended by other types, like:
```ts
interface WidevineModularDRMConfig extends DRMConfig {
  //...
}
```
I would propose renaming it to `BaseDRMConfig` if there are some common fields.
Then the `DRMConfig` would be:
```ts
interface DRMConfig = {
  playready: PlayReadyDRMConfig;
  widevine: WidevineModularDRMConfig;
  // ...
}
```
Which is correct type of `SourceConfig` `drm` property, according to docs:
https://bitmovin-a.akamaihd.net/bitmovin-player/stable/7/docs/interfaces/playerconfigapi.sourceconfig.html

**Comment by 19majkel94** [comment]
Great! Is there any ETA for this or I could help you? 😉

**Comment by protyposis** [comment]
Fixed in type definitions of `bitmovin-player@8`. Broken local player type definitions in UI package have been removed.
