### ISSUE TITLE
Safari on Mac emits onPlayerResize event constantly

### ISSUE THREAD

**Issue by ireneuszsawicki** [bitmovin/bitmovin-player-ui#11]
Hi Guys,

Safari on Mac is constantly emitting onPlayerResize event blocking the player from loading. It's happening on the latest branch release/v2.0.0-rc1 build with all default settings (player JS loaded from beta channel). It's behaving that way on the latest and few last versions of Safari.
According to the release notes I think it was fixed once in v6.1.8

![bitmovin-onresize-bug](https://cloud.githubusercontent.com/assets/4947745/24900026/bcf1c488-1ea2-11e7-9077-8fe12b463895.png)

**Comment by protyposis** [comment]
Thanks for reporting. This is not a UI issue so I'm closing this and will open a player issue in our internal bug tracker.
