### ISSUE TITLE
TvNoiseCanvas.renderFrame called after player.destroy

### ISSUE THREAD

**Issue by unki2aut** [bitmovin/bitmovin-player-ui#15]
After `player.destroy()` also the UI should be destroyed correctly.

Steps to reproduce:

1. Load the player with the UI and force an error (e.g. set an unreachable URL as source).
1. Call `player.destroy()`
1. Pause the JS execution and it will probably land somewhere in `TvNoiseCanvas.renderFrame`

**Comment by protyposis** [comment]
Fixed in cfaf6a320ee5fe7b7023cbe66c4af39a6beb2df3 and released in `v2.5.0`
