### ISSUE TITLE
.player is not a function

### ISSUE THREAD

**Issue by josephlodero** [bitmovin/bitmovin-player-ui#157]
Can some one help me how to import Bitmovin player??

Im using Ionic3

Error : 
![image](https://user-images.githubusercontent.com/11495107/45014879-8c276900-b052-11e8-835d-1c8ecc521c1e.png)

**Comment by josephlodero** [comment]
"bitmovin-player-ui": "^2.18.0"

and i just imported it in my page.
import * as bitmovinPlayer from 'bitmovin-player-ui'

  constructor(
  ) {
    let player = bitmovinPlayer.player('id');
    let config = {
      source: {
        dash: 'https://path/to/mpd/file.mpd',
        hls: 'https://path/to/hls/playlist/file.m3u8',
        smooth: 'https://path/to/manifest/file/Manifest'
      }
    }
    
    player.setup(config).then(
      function(player) {
        console.log('Successfully created Bitmovin Player instance');
      },
      function(reason) {
        console.log('Error while creating Bitmovin Player instance');
      }
    );
  }

**Comment by protyposis** [comment]
If you really are importing the *player* from the *UI* package, that's the issue. For the player you need `bitmovin-player` instead of `bitmovin-player-ui`.

**Comment by stonko1994** [comment]
Another thing: You need to move the player initialization to the `ionViewDidEnter` method or at least out of the constructor. Because the HTML and therefore the `#player` isn't accessible there.

**Comment by stonko1994** [comment]
First you could use lastest release version:
```json
"bitmovin-player": "^7.8.3",
"bitmovin-player-ui": "^2.18.0",
```

A working sample for ionic look like:
in the `html` file:
```html
<ion-content>
...
<div id="player"></div>
...
</ion-content>
```
in the `ts` file: 
```ts
  import bitmovinPlayer from 'bitmovin-player';
  import bitmovinPlayerUI from 'bitmovin-player-ui';

  ...

  ionViewDidEnter() {
    let config = {
      key: 'YOUR KEY HERE',
      style: {
        ux: false,
      },
      source: {
        progressive: '//bitdash-a.akamaihd.net/content/sintel/Sintel.mp4',
        poster: '//bitdash-a.akamaihd.net/content/sintel/poster.png',
      }
    };

    let player = bitmovinPlayer('player');
    player.setup(config).then(() => {
      let uiManager = bitmovinPlayerUI.UIManager.Factory.buildDefaultUI(player, {});
      console.log('success');
    }).catch(() => {
      console.log('failure');
    })
  }
```

For the css for the `playerUI` follow [these](https://www.joshmorony.com/including-custom-css-files-in-the-ionic-build-process/) steps and add `@import 'bitmovinplayer-ui';` to your `.scss` file

**Comment by josephlodero** [comment]
Hi! Thank You for your help..
I already follow your instruction and i got this error: 
![image](https://user-images.githubusercontent.com/11495107/45273780-bfe90f80-b4e6-11e8-92ff-fdd224e76954.png)

**Comment by josephlodero** [comment]
okay i already got it.
i just included this to my copy.config.js:
![image](https://user-images.githubusercontent.com/11495107/45277488-a9e54a00-b4fa-11e8-942d-2c46f0ca2b5f.png)

**Comment by josephlodero** [comment]
Hi @stonko1994 
can you please help me with these error?
![image](https://user-images.githubusercontent.com/11495107/45398392-7a5b4c80-b676-11e8-9f54-44f41a1a5a58.png)
it always happen when im going back to the list of video and revisit the page

**Comment by stonko1994** [comment]
Unfortunately this stacktrace doesn't provide much information. But it seems that it's not UI related.

**Comment by h0jeZvgoxFepBQ2C** [comment]
> Hi! Thank You for your help.. I already follow your instruction and i got this error: ![image](https://user-images.githubusercontent.com/11495107/45273780-bfe90f80-b4e6-11e8-92ff-fdd224e76954.png)

I have this issue now, with the latest version. @josephlodero where do you set this config?
