### ISSUE TITLE
Timeline markers are not updating after switching source

### ISSUE THREAD

**Issue by stonko1994** [bitmovin/bitmovin-player-ui#163]
When you load a source with `timeline-markers` (`source.markers`) first and afterwards loading a source **without** timeline-markers the old ones are still there.

Similar could happen to `recommendations` `title` & `description`.

Affected Versions: 2.18.x / 3.x

EDIT:
This happened because the `uiConfig` was not copied but merged with the config passed to the player.

**Comment by protyposis** [comment]
Fixed in `3.0.0`
