### ISSUE TITLE
SetupError(1025) - Player is already set up

### ISSUE THREAD

**Issue by josephlodero** [bitmovin/bitmovin-player-ui#170]
First load of the page the player is okay, but every time i go back and revisit the page this error occur:

![image](https://user-images.githubusercontent.com/11495107/45285159-153c1580-b515-11e8-9e07-9848409bd91b.png)

**Comment by protyposis** [comment]
This is not related to the UI. But it seems that you are calling `setup` on a player instance on which `setup` has already been called before.
