### ISSUE TITLE
Enable playback speed selector by default

### ISSUE THREAD

**Issue by bitmovin-kenny** [bitmovin/bitmovin-player-ui#184]
In https://github.com/bitmovin/bitmovin-player-ui/pull/125 we introduced a flag to hide the PlaybackSpeedSelectionBox, we also accidentally disabled the Selection by default.

The default should be to show the PlaybackSpeed Selection Box.

**Comment by protyposis** [comment]
Didn't we do that on purpose? Actually I like this change and think this is a rather unimportant feature which makes sense to be opt-in.

**Comment by dweinber** [comment]
It was not intended to change the default from my point of view.

**Comment by protyposis** [comment]
It's even in the changelog, how could that happen "accidentally"?

**Comment by protyposis** [comment]
Fixed in https://github.com/bitmovin/bitmovin-player-ui/pull/198 & https://github.com/bitmovin/bitmovin-player-ui/pull/199
