### ISSUE TITLE
Watermark too small in IE11

### ISSUE THREAD

**Issue by protyposis** [bitmovin/bitmovin-player-ui#187]
Since #180 is merged, the watermark in IE11 is too small:

![image](https://user-images.githubusercontent.com/189372/46402063-06edad80-c6ff-11e8-89cd-5b2d04439a52.png)

Seems like `background-size: initial` does not work as intended there.

**Comment by stonko1994** [comment]
This is also the case in #183. I found out that there is an [issue](https://stackoverflow.com/questions/37707969/ie11-wont-background-size-cover) in IE

**Comment by dweinber** [comment]
IE11 is not a supported platform anymore: https://developer.bitmovin.com/playback/docs/supported-platforms-devices-player
