### ISSUE TITLE
Changing the volume while muted should also unmute the player

### ISSUE THREAD

**Issue by Reevn** [bitmovin/bitmovin-player-ui#189]
Starting with `v8.0.0` we now separate between being in a `muted` state and the volume being set to 0. When the player is in the `muted` state and the volume is changed, the player will not accept the new volume and still stay in the `muted` state.

Optimally, we would also unmute the player when changing the volume.

**Comment by protyposis** [comment]
This was done by the player itself in v7 and the UI was not adjusted to the changed v8 behavior. Simply calling `unmute` on a volume change event should fix this.

**Comment by protyposis** [comment]
Fixed in https://github.com/bitmovin/bitmovin-player-ui/pull/200
