### ISSUE TITLE
Update to gulp4

### ISSUE THREAD

**Issue by michael-riha** [bitmovin/bitmovin-player-ui#208]
I did a checkout today and ran into this issue https://github.com/gulpjs/gulp/issues/2162

`npm 6.5.0`
`node v11.5.0` but the same with which I had before  `node v10.0.2`

**Comment by protyposis** [comment]
Update to Gulp 4 is not planned. Did you try any of the workarounds in the linked issue?

**Comment by michael-riha** [comment]
yes but they are messy on a global scope of NPM.

**Comment by protyposis** [comment]
Simply using Gulp 4 seems to solve the issue. No need to adjust the `gulpfile`.

**Comment by michael-riha** [comment]
shouldn't it be documented somewhere?
repo package.json still fetches 3.9.1 and breaks.
