### ISSUE TITLE
Setting startTime stops any playback

### ISSUE THREAD

**Issue by TomGrundy** [bitmovin/bitmovin-player-ui#21]
Setting startTime in options when setting up the player causes playback to halt. The video loads, and all other player features appear to work, but actual playback can never be initiated.

Steps to reproduce:
1. Load the player, e.g. `var player = bitmovin.player('player-wrapper');`
2. call `player.setup(config)`, with config containing some arbitrary start time in seconds, e.g. `{ options: { startTime: 123 }`
3. Attempt to play the video. Note that the player fetches the content, and all player functionality appropriately fires the correct events, but playback never actually starts.

**Comment by protyposis** [comment]
Hi Tom, I cannot reproduce this issue. Can you post a simple example snippet to reproduce the issue?

**Comment by protyposis** [comment]
Closing due to lack of feedback.
