### ISSUE TITLE
is bitmovin player v8.1.0 considered stable?

### ISSUE THREAD

**Issue by chovy** [bitmovin/bitmovin-player-ui#211]
I can't get a lot of documented features to work.

For example headers object in drm blocks don't get sent. And network prehttpProcessor only works in chrome not safari.

I'm using http://cdn.bitmovin.com/player/web/8/bitmovinplayer.js

and i'd say its alpha

**Comment by LudoMichaud** [comment]
Hi, 
Thanks for reaching out. 

>is bitmovin player v8.1.0 considered stable
Yes, 8.1.0 is already released as Stable.

>For example headers object in drm blocks don't get sent
Please feel free to send your player configuration or a demo page to support@bitmovin.com. Me and my colleagues from the support team will then be happy to have a look into this. 

> network prehttpProcessor only works in chrome not safari.
When it comes to Safari, the Bitmovin Player is using Safari Native player by default and requests are directly performed by the Native player. it is therefore not possible to customise request before they are being sent, as you can do when the HTML5 player is used. Please feel free to send an email to support@bitmovin.com with a bit more details about what you would need to achieve. We're happy to help.

**Comment by dweinber** [comment]
@chovy did you also check our [v7 to v8 Migration Guide](https://bitmovin.com/docs/player/tutorials/migration-guide-v7-to-v8#other-changes)? Please note that the header objects in 8.0+ are simplified. 

In v7 an array of objects was used:
```
headers: [
  {
    name: 'X-Custom-Header-Name',
    value: 'customHeaderValue'
  },
  {
    name: 'X-Header2',
    value: 'value2'
  }
]
```
In v8 it's now simply an object:
```
headers: {
  'X-Custom-Header-Name': 'customHeaderValue',
  'X-Header2': 'value2'
}
```
