### ISSUE TITLE
Persist Users Video Quality Selection

### ISSUE THREAD

**Issue by ijones16** [bitmovin/bitmovin-player-ui#213]
bitmovin.player.version: ^7.8.2
bitmovin.playerui.version: 2.18.0

I've tried saving the user video quality bit rate a couple of different ways and nothing seems to work. 

1. store their selection in localStorage and try to load that startupBitrate bit rate.
2. store the id of the bitrate in localStorage and set the bit rate based on that id
    - I found that the id for the same bitrate across multiple videos is different so this is kind of useless. 

Is this a bug or am I missing something completely? I've scoured the docs for more time than I'd like to admit.

**Comment by protyposis** [comment]
Hi, your observation is correct. The ID for the bitrate is usually defined in the manifest of the video and can vary from source to source. To maintain similar video quality IDs over multiple videos, you need to handle that on the video storage or encoding side and make sure that their manifests have a common format. If you know the desired bitrate, a more flexible approach would be to iterate the available qualities and select the quality with the closest bitrate.

This is not related to the UI so I'm closing this issue. For player support please write to support@bitmovin.com.

**Comment by ijones16** [comment]
Thanks for the response @protyposis
