### ISSUE TITLE
Use of Prettier/large diffs when maintaining custom UI

### ISSUE THREAD

**Issue by alexanderte** [bitmovin/bitmovin-player-ui#214]
I’m currently setting up a custom UI, and I need to maintain my own version of `bitmovin-player-ui`. I like to use Prettier with format-on-save enabled, both because it takes the hassle out of formatting code, but also because it is easy to detect wether or not the code compiles.

Are you using/have you considered using Prettier internally – and in any case would you share your settings? That would make the diffs a lot smaller.

**Comment by protyposis** [comment]
Hi, we have considered using Prettier but decided against it for the time being. We want to keep changesets as small as possible and adjust our code style progressively as PRs are merged to avoid one large reformatting PR that basically "resets" Git blame functionality.

**Comment by alexanderte** [comment]
Thanks for the quick response. I totally understand. I will rather see if I can disable Prettier for this particular project.
