### ISSUE TITLE
how to run the example?

### ISSUE THREAD

**Issue by aranmohyeddin** [bitmovin/bitmovin-player-ui#215]
I'm sorry I guess this is a silly question but I fail to run the example.

I cloned the repo just now. I went to `src/html` and ran `python -m http.server` then it said it failed to find the script `bitmovinplayer-ui.js` sp I created a directory called `js` and downloaded the file from `http://cdn.bitmovin.com/player/web/8/bitmovinplayer-ui.js` into that directory then I ran my python server and opened index.html but the loaded page is very messy and it doesn't do anything there are just many black boxes and buttons and texts in the screen. Here is what I get in browser console:
```
adaptive Video Streaming Service by www.bitmovin.com bitmovinplayer.js:11:1058786
Player Version 8.1.0 bitmovinplayer.js:11:1058786
source successfully loaded localhost:8000:264:7
XML Parsing Error: syntax error
Location: http://localhost:8000/
Line Number 1, Column 1:
localhost:8000:1:1
source successfully loaded localhost:8000:264:7 
```
I also tried to simply open the index.html file with firefox and it didn't work either. would you please be so kind as to explain to me step by step how I should run the examples?

**Comment by dweinber** [comment]
Please have a look at https://github.com/bitmovin/bitmovin-player-ui/blob/master/README.md#getting-started-with-development, it outlines the necessary steps and
available options. Please let me know if there are still open questions.
