### ISSUE TITLE
Handling custom state in player UI

### ISSUE THREAD

**Issue by alexanderte** [bitmovin/bitmovin-player-ui#216]
I’m trying to implement functionality to create clips within a video. Each clip has a start and end time. Extending the UI within the player is mostly done, and follows the same patterns as the rest of the UI (many small components that are composed in `UIManager.Factory`). However, I need to share state between these components, and besides using local storage it’s unclear to me what my options are. I see that many existing components gets state from the player itself, but it’s probably not meant to be extended?

Could you point me in the right direction? Please let me know if this is more of a support issue, and I’ll use that channel instead.

**Comment by stonko1994** [comment]
There is actually no 'state handling object' in the UI since the player has the state.

But maybe the simplest solution would be to extend the `config` for your components which needs a state handling object and pass it in.

**Comment by alexanderte** [comment]
I understand.

That sounds like something I could try. Thanks for the help!
