### ISSUE TITLE
`player.seek` occationally jumps to an earlier position than specified

### ISSUE THREAD

**Issue by alexanderte** [bitmovin/bitmovin-player-ui#218]
I’ve created my own instance of the player and loaded the Parkour video. I’m implementing custom UI to create and playback clips. When I do `player.seek(24.979331)` repeatedly by clicking a custom made button, it goes to the correct time most of the times. However, occationally it goes to around 19.95. I have logged to console the exact time that I’m seeking to, and the `ON_SEEKED` event handler logging the result of calling `player.getCurrentTime()` immediately after being triggered. Here is the output in DevTools console:

    {currentTime: 24.979331}
    playbackclipbutton.ts:38 EVENT.ON_SEEKED {payload: {…}, currentTime: 24.98}
    playbackclipbutton.ts:38 EVENT.ON_SEEKED {payload: {…}, currentTime: 24.98}
    playbackclipbutton.ts:38 EVENT.ON_SEEKED {payload: {…}, currentTime: 24.98}
    playbackclipbutton.ts:38 EVENT.ON_SEEKED {payload: {…}, currentTime: 24.98}
    playbackclipbutton.ts:38 EVENT.ON_SEEKED {payload: {…}, currentTime: 19.952505}
    playbackclipbutton.ts:38 EVENT.ON_SEEKED {payload: {…}, currentTime: 24.98}
    playbackclipbutton.ts:38 EVENT.ON_SEEKED {payload: {…}, currentTime: 19.946666}
    playbackclipbutton.ts:38 EVENT.ON_SEEKED {payload: {…}, currentTime: 24.98}
    playbackclipbutton.ts:38 EVENT.ON_SEEKED {payload: {…}, currentTime: 24.98}
    playbackclipbutton.ts:38 EVENT.ON_SEEKED {payload: {…}, currentTime: 24.98}
    playbackclipbutton.ts:38 EVENT.ON_SEEKED {payload: {…}, currentTime: 24.98}

I could not reproduce this by using the Bitmovin Player UI Demo using the predefined seek function calls. But in my customized player UI, I don’t do any other function calls that should affect playback.

Is this a known issue? Do you know about any fix or workaround?

**Comment by stonko1994** [comment]
Since you are using the player API `player.seek(…)` this sounds to be unrelated to the UI.

For player support please contact [support@bitmovin.com](mailto:support@bitmovin.com) for further help.

**Comment by alexanderte** [comment]
I understand – I will try that. Thanks!
