### ISSUE TITLE
Percentage Incorret

### ISSUE THREAD

**Issue by lucassouzamiranda** [bitmovin/bitmovin-player-ui#219]
Hi,

The percentage shown is not correct. It's going from 0 to 100 all at once.

TS: bufferingoverlay.ts

**Comment by protyposis** [comment]
The buffering overlay does not display a percentage so I'm afraid I do not know what you are referring to.

Please feel free to reopen with a detailed documentation of the issue or precise instructions on how to reproduce your issue.
