### ISSUE TITLE
Enable seeking to exact clicked position within timeline markers

### ISSUE THREAD

**Issue by alexanderte** [bitmovin/bitmovin-player-ui#227]
Is it possible to enable clicking within a marker and seek to the exact clicked position – i.e. as it would if there were no markers? What seems to happen by default is that it seeks to the starting marker. I had a look at `seekbar.ts` and `uiconfig.ts`, but I was not able to find any timeline marker click events.

**Comment by protyposis** [comment]
Hi, there is currently no config option to disable the marker snapping behavior, but you can find the code that handles it here:

https://github.com/bitmovin/bitmovin-player-ui/blob/f928fc0c787d43510cc8b95bbfe966ce2c0d1348/src/ts/components/seekbar.ts#L899-L918

**Comment by alexanderte** [comment]
Thanks for the quick reply. I’ll see if I can figure it out.
