### ISSUE TITLE
Subtitle or Audio select on demofactory not close UI

### ISSUE THREAD

**Issue by vfernandes0408** [bitmovin/bitmovin-player-ui#234]
This bug is related a demofactory.ts.
When i use this ts and set another subtitle different default has the problem that ui not hidden.

**Comment by stonko1994** [comment]
Thanks for reporting we will look into it.

**Comment by vfernandes0408** [comment]
Any news about this issue ?

**Comment by stonko1994** [comment]
We were able to reproduce the issue and we have an internal issue open but there's no ETA for a fix at this time.
