### ISSUE TITLE
Seek bar position marker not moving after a paused ad is skipped

### ISSUE THREAD

**Issue by Reevn** [bitmovin/bitmovin-player-ui#246]
If one pauses an ad and skips it, the seek bar position marker is not re-activated.

This is probably because a `Paused` event is received but no `Play` or `Playing` event follows.

The semantic of the `AdBreakFinished` event is that the main content has been restored and is playing, so the marker should probably also be re-activated on that event.

**Comment by protyposis** [comment]
> The semantic of the `AdBreakFinished` event is that the main content has been restored and is playing

Are you sure about that? Why does `AdBreakFinished` carry a notion of the playback state? If one pauses an ad and then skips it, the next ad or content should not play back as playback has been paused. Only a call of `play()` should continue playback and it's `Play`/`Playing` events will tell listeners that this is indeed the case. Play state should be correctly trackable even when not listening to any ad events and acting like everything (content + ads) is a single stream.

**Comment by Reevn** [comment]
This is a player issue and not a UI issue. Closing this ticket.
