### ISSUE TITLE
[Subtitiles] Subtitle duplicate 

### ISSUE THREAD

**Issue by lucassouzamiranda** [bitmovin/bitmovin-player-ui#256]
I was testing the new bitmovin version and came across the subtitle problem.

When I pass the mouse it has two subtitles.

![image](https://user-images.githubusercontent.com/47158821/63454491-4b6e5e80-c421-11e9-8e67-d27ef6f5df29.png)

**Comment by LudoMichaud** [comment]
Hi @lucassouzamiranda ,
I haven't managed to reproduce with one of our test pages [1], as it seems. 

What I would recommend incase you need us to have a closer look, would be to open a ticket with our Support Team by providing your findings, player version and tests stream to support@bitmovin.com. 

[1] https://bitmovin.com/demos/multi-audio-tracks

We're looking forward to reading from your side.
Thanks
