### ISSUE TITLE
[Subtitles Settings] ListBox

### ISSUE THREAD

**Issue by lucassouzamiranda** [bitmovin/bitmovin-player-ui#257]
Good afternoon,

I wonder if you can put these settings in ListBox mode.
I am trying to configure and it is as follows
![image](https://user-images.githubusercontent.com/47158821/64280728-1b967f00-cf28-11e9-997a-fc40e4c1cbe2.png)

And it would look like this.

![image](https://user-images.githubusercontent.com/47158821/64281503-a9269e80-cf29-11e9-959a-e8aa5bed7d5b.png)

**Comment by lucassouzamiranda** [comment]
Open ticket in https://github.com/bitmovin/telecine-sync/issues/43

**Comment by stonko1994** [comment]
Currently, there is no default element to display those as `ListBox`.

**Comment by lucassouzamiranda** [comment]
Could you include in the listbox?

**Comment by stevegeiger** [comment]
Closing the copy of the ticket in our UI repo in favor of the customer sync, as we will not incorporate this functionality into our default UI.
