### ISSUE TITLE
window is not defined

### ISSUE THREAD

**Issue by justinmoon** [bitmovin/bitmovin-player-ui#283]
I'm trying to use `bitmovin-player` in a [next.js](https://nextjs.org/) (server-side rendered react.js) project.

When I attempt to import the `Player` and run it, I get a `window is not defined` error. [Here is a minimal reproduction of this bug](https://github.com/justinmoon/window-not-defined).

I borrowed the main [react.js component in this demo](https://github.com/justinmoon/window-not-defined/blob/master/pages/index.js) directly from your [react.js example](https://github.com/bitmovin/bitmovin-player-web-samples/blob/master/react/reactjs.html). And I'm importing `Player` exactly as is done in your [webpack example](https://github.com/bitmovin/bitmovin-player-web-samples/blob/master/webpack-demo/src/index.js#L1) ...

**Comment by justinmoon** [comment]
It seems like [this PR](https://github.com/bitmovin/bitmovin-player-ui/pull/244) was made to help support server-side rendering, but I'm not sure exactly how I'd utilize those utilitites ...

**Comment by LudoMichaud** [comment]
Hi, 
Thanks for reaching out and for sharing your sample project. 
Our player needs to be instantiated on the client side, and the `window` object is required. 

You could for instance use RequireJS, as shown in one of our [sample projects](https://github.com/bitmovin/bitmovin-player-web-samples/blob/master/requirejs-demo/buildPlayerWithRequirejs.html)

Let us know in case you have any questions.

**Comment by LudoMichaud** [comment]
> https://github.com/bitmovin/bitmovin-player-ui/issues/283#issuecomment-555214407
This PR only concerns the UI (not the Player Web SDK itself) and might only affect cases where the UI is used with our Native SDKs

**Comment by justinmoon** [comment]
Thanks @LudoMichaud.

In case any next.js developers stumble upon this issue in the future, [this is what I needed to do](https://github.com/justinmoon/window-not-defined/commit/fe94613f3a62633d5cdc2b7cf32e9a0424b2b565) to prevent the video player from running on the server and only running it on the client where `window` exists.
