### ISSUE TITLE
Box-shadow around whole player

### ISSUE THREAD

**Issue by Andersos** [bitmovin/bitmovin-player-ui#286]
Why was this changed and/or added in https://github.com/bitmovin/bitmovin-player-ui/commit/0a22d395c6598fe25a03d24bfd7af4102483e1e9#diff-0bf70d2156c3080419da1d0c15a21146

We have now started to see a blue box-shadow around the player. 
![Screenshot 2020-01-15 at 10 20 56](https://user-images.githubusercontent.com/288977/72421430-c3e30c80-3780-11ea-811b-b20f3e540081.png)

**Comment by stonko1994** [comment]
With the latest release [3.9.2](https://github.com/bitmovin/bitmovin-player-ui/compare/v3.9.1...v3.9.2) we added support for `Web Content Accessibility (WCAG) 2.0`. And for that, we needed to add support for users to see that the player (which UI component) is currently focused.

**Comment by Andersos** [comment]
Why is this then not added to the player but instead there is a transparent button element?

**Comment by stonko1994** [comment]
The player (plain-video) itself does not handle any user interaction. 

The box-shadow is added to the `HugePlaybackToggleButton` when it is focused.
