### ISSUE TITLE
Occasional error on Safari "Observed duplicate need key event with initData"

### ISSUE THREAD

**Issue by roenschg** [bitmovin/bitmovin-player-ui#327]
Dear Bitmovin team,

we currently experience weird behavior.

We have a video in the HLS format encrypted with HLS. We want to play that video on Safari and it works in ~2 out of 5 requests.

In the other request we get in the logs the error "A decryption key error was encountered". The full log can be seen here:
![959be6bc-3087-4b04-b8e9-86112676aab3](https://user-images.githubusercontent.com/9590236/93218807-ec396580-f76a-11ea-9dc1-baf049949b1c.png)
![image (2)](https://user-images.githubusercontent.com/9590236/93218828-f2c7dd00-f76a-11ea-815e-82a5447c7d15.png)

We use the player option `fairplay_ignore_duplicate_init_data_key_errors`. Without the option the video cannot be played at all. If we set the option to `true` it sometimes takes up to 30 seconds until the video plays, without any network activity.

Can someone please help us here?

Best Regards,
Gerd Rönsch

**Comment by dweinber** [comment]
Hi @roenschg,
As the reported problem is not an issue of the bitmovin-player-ui, I'm closing this issue.

Please submit bug reports or other problems via https://bitmovin.com/dashboard/support/cases/create?tab=player. Thank you!

**Comment by roenschg** [comment]
@dweinber can you please describe why this is not an issue of the bitmovin-player?

The player takes a really long time until the video can be played and other players don't have the issue with the same videos.

The player even throws that notice/error but there is no documentation anywhere about the underlying issue. I even use an option that I got from bitmovin support that I later found out is nowhere documented.(fairplay_ignore_duplicate_init_data_key_errors)

**Comment by dweinber** [comment]
@roenschg this repository is just about the player's **UI**, not the player itself. Your issue doesn't seem to be related to the UI, or am I missing something?

**Comment by roenschg** [comment]
Hi @dweinber I reported a bug now to Bitmovin itself.

**Comment by dweinber** [comment]
Thanks!
