### ISSUE TITLE
Chromecast cookies

### ISSUE THREAD

**Issue by martinop** [bitmovin/bitmovin-player-ui#331]
Hi, I'm using these options for the player:
```
key: process.env.REACT_APP_BITMOVIN_LICENSE,
options: {
withCredentials: true,
   hlsManifestWithCredentials: true, 
   hlsWithCredentials: true,
   manifestWithCredentials: true
},
remotecontrol: { type: 'googlecast' },
```

I'm using signed cookies and it's working on the web but when I try to use on the chromecast I get: "Network error while downloading"

Is supposed that chromecast use cookies automatically (with credentials true)? I don't see more options in remoteControl

**Comment by dweinber** [comment]
As this is no UI-related issue, I'd kindly ask you to open a support request via your dedicated support route or via https://bitmovin.com/dashboard/support/cases/create?tab=player.
Thanks for your understanding.
