### ISSUE TITLE
SOURCE_HLS_STREAM_ERROR with Safari Native Player

### ISSUE THREAD

**Issue by anajuliabit** [bitmovin/bitmovin-player-ui#360]
Browser: Safari
OS: Mac OS/IOS
Device: Mac/Iphone 12
SDK Version: 8
 
To work videos with AES key on Safari Native Player, I need send in bitmovin `player.load()` a route to my company server whose gets HLS playlist from cdn and changes EXT-X-KEY. Bitmovin get master and video playlist, but don't get audio playlist and neither chunk's of the video.

![Screen Shot 2021-01-14 at 10 54 56](https://user-images.githubusercontent.com/50335980/105174051-bdf4d980-5b00-11eb-9714-b146198ac591.png)

![Screen Shot 2021-01-18 at 16 03 19](https://user-images.githubusercontent.com/50335980/105173949-88e88700-5b00-11eb-81d0-35fddcf6bdf2.png)

Obs: When I try on Google Chrome, works perfectly.

**Comment by dweinber** [comment]
Hi @anajuliabit,
As this issue is not related to the player's UI, I'm closing the issue in this repository. Please create a support ticket in our dashboard instead: https://bitmovin.com/dashboard/support/cases/create?tab=player
