### ISSUE TITLE
PlaybackToggleButton does not work when initiated through bitmovin.playerui.UIManager

### ISSUE THREAD

**Issue by ireneuszsawicki** [bitmovin/bitmovin-player-ui#4]
Hi,

PlaybackToggleButton (that small play button on the bottom-left side) does not seem to work when it's set in UI container via bitmovin.playerui.UIManager. Clicking on it emits events however it's not doing anything with the player playback. Neither playing (when video is paused) nor pausing does not work. HugePlaybackToggleButton seems to work fine.

Simplest UI which reproduces this error is attached.

[sample-code.txt](https://github.com/bitmovin/bitmovin-player-ui/files/742423/sample-code.txt)

best,
Irek

**Comment by protyposis** [comment]
Your code is a bit confusing but if you look closely you'll notice that you're adding the `PlaybackToggleButton` to the UI component tree twice. Because of that, the button is initialized twice, two click handlers are added, and a click on the button always triggers the first handler that executes play/pause, followed by the second handler that immediately inverts the action. This leads to the impression that the button is not working.

**Comment by ireneuszsawicki** [comment]
Hi protyposis,

It's just shortened version of more complicated UI I was trying to build with several if's around. That's why it can look bit weird.

I can't find that double `PlaybackToggleButton` insertion. Can you point the place where it is or what causes it?
Please note that there're `PlaybackToggleButton` and `PlaybackToggleOverlay` declarations only. `PlaybackToggleButton` itself doesn't seem to be inserted twice.

best,
Irek

**Comment by protyposis** [comment]
I commented the interesting lines of you code sample:

```js
var bitmovinUiConfig = {
  components: [
    new bitmovin.playerui.BufferingOverlay(),
    new bitmovin.playerui.PlaybackToggleOverlay()
  ],
  cssClasses: ['ui-skin-modern']
};
bitmovinUiConfig.components.push(new bitmovin.playerui.CastStatusOverlay());
var bitmovinControlBarButtonsConfig = {
  components: [],
  cssClasses: ['controlbar-bottom']
};
// First, you add the PlaybackToggleButton to the bitmovinControlBarButtonsConfig once, which is fine :)
bitmovinControlBarButtonsConfig.components.push(new bitmovin.playerui.PlaybackToggleButton());
// Then, you create a Container from the bitmovinControlBarButtonsConfig that contains the button. Still fine.
var bitmovinControlBarButtons = new bitmovin.playerui.Container(bitmovinControlBarButtonsConfig);
// Next, you create a ControlBarConfig with the above Container (containing the button) as a child. Still fine.
var bitmovinControlBarConfig = {
  components: [
    bitmovinControlBarButtons,
  ]
};
// Last, you push to the above config, which already contains a child Container with the button, a second
// Container with the same bitmovinControlBarButtonsConfig that the previous Container was configured
// with. This config still contains the PlaybackToggleButton, which is therefore added for a second time here!
bitmovinControlBarConfig.components.push(
  new bitmovin.playerui.Container(bitmovinControlBarButtonsConfig)
);
bitmovinUiConfig.components.push(new bitmovin.playerui.ControlBar(bitmovinControlBarConfig));
bitmovinUi = new bitmovin.playerui.UIContainer(bitmovinUiConfig);
uiManager = new bitmovin.playerui.UIManager(player, bitmovinUi, null);
```

**Comment by protyposis** [comment]
Added a check in the dev branch. Such cases will now be detected and throw an error.

**Comment by ireneuszsawicki** [comment]
Thanks a lot, this was very tricky. 
What you've mentioned was the cause. After I've removed that unnecessary play button config it works fine. I've checked it like a thousand times before posting this issue report.

So just to clarify, some (or all) of the components can't appear in the UI config more than once?

**Comment by protyposis** [comment]
Yeah that was a tricky case :) The added check will catch that in the future.

You _can_ have _multiple instances of the same component_ in the UI, but you _can't_ have the _same instance in multiple places_ of the UI. This applies to all components.

It's currently also not possible to shuffle components between different positions in the UI (e.g. dynamically removing from one container and adding to another). The UI structure, once passed to the UI manager, is immutable. If you need the same component in multiple places, you need to add multiple instances and "switch" between them by changing their visibility with the `show()`/`hide()` methods.

**Comment by ireneuszsawicki** [comment]
I see. Thanks a lot for all these explanations!
