### ISSUE TITLE
[Question] Headless live Dash player used for load or presence testing

### ISSUE THREAD

**Issue by mlondon1** [bitmovin/bitmovin-player-ui#42]
Hi,
Is there a way to run the Bitmovin player "headless" (without GUI, run from a command line) in order to verify the feed requests result in non 4XX/5XX errors, and also to possibly do load testing?

**Comment by protyposis** [comment]
We have not tested it but you could give [Headless Chrome](https://developers.google.com/web/updates/2017/04/headless-chrome) a try.

**Comment by protyposis** [comment]
Closing due to lack of feedback.
