### ISSUE TITLE
npm ERR! Build failed with error code: 1 while running npm install 

### ISSUE THREAD

**Issue by brandontan-888** [bitmovin/bitmovin-player-ui#422]
Hi, I got the following error while attempting to run `npm install `. Please advise. 
[2021-12-31T05_51_31_702Z-debug-0.log](https://github.com/bitmovin/bitmovin-player-ui/files/7795416/2021-12-31T05_51_31_702Z-debug-0.log)

**Comment by felix-hoc** [comment]
Unfortunately a dependency seems to cause issues with newer node versions. We will look into it.
As a workaround in the meantime, I'd suggest to try node v12 (verified) or node v14 (unverified, but seems to work as well).

**Comment by ravloony** [comment]
This is now fixed, and the build works for all node versions from 10 to 16.
