### ISSUE TITLE
Bitmovin encoding distorts colors

### ISSUE THREAD

**Issue by ulshv** [bitmovin/bitmovin-player-ui#453]
After encoding, video recorded on iPhone 13 Pro with HDR enabled has very different colors in the resulting video. 
Screenshots of original video (left) and after encoding (right):

<img width="500" alt="Screen Shot 2022-03-21 at 8 04 53 PM" src="https://user-images.githubusercontent.com/16082811/161301085-3a426003-a14e-43e7-87a2-73025dab3e88.png">

Not sure where I should report about this issue, but this repository seems to be the most active.

Here's configuration part for encoding:
```javascript
new H264VideoConfiguration({
    name: `H.264 720p`,
    presetConfiguration: PresetConfiguration.VOD_STANDARD,
    height,
    bitrate,
});
```
Muxing:
```javascript
new Fmp4Muxing({
    segmentLength: 4.0,
    outputs: [buildEncodingOutput(output, outputPath)],
    streams: [new MuxingStream({ streamId: stream.id })],
});
```

**Comment by dweinber** [comment]
Hey @ulshv, this Github repository is hosting the Bitmovin Player UI project, but your question is not related to that. Hence, I'm closing this issue.

Please feel free to reach out to us via bitmovin.com/dashboard or visit our community site: https://community.bitmovin.com/
