### ISSUE TITLE
Livestream stutters at higher playback speed

### ISSUE THREAD

**Issue by damian-blaszczak** [bitmovin/bitmovin-player-ui#469]
**Browser**: Chrome
**OS**: Mac OS
**Device**: Mac

**URL**: https://bitmovin.com/demos/stream-test?format=dash&manifest=https%3A%2F%2Fakamaibroadcasteruseast.akamaized.net%2Fcmaf%2Flive%2F657078%2Fakasource%2Fout.mpd

**Steps to reproduce:**
1. Open Stream URL
2. Do not rewind and change playback speed to 2x

### Description
**Current behaviour:**

When watching a livestream at 2x video speed it starts to stutter, waits for buffering and so on.

**Expected behaviour:**
In this case playback speed should automatically change to "normal".

**Comment by dweinber** [comment]
Hi,
This issue is not related to the player UI project, hence I'm closing it. Please open a ticket in the [Bitmovin Dashboard](https://bitmovin.com/dashboard/support/tickets).
