### ISSUE TITLE
CC/Subtitle Option Missing in IE11

### ISSUE THREAD

**Issue by kimtran23-mg** [bitmovin/bitmovin-player-ui#48]
Subtitles option in the settings panel does not appear in IE11.
On all other browsers, the video quality, speed and subtitles option are visible, but on IE11, the subtitles option is missing.

![image](https://user-images.githubusercontent.com/30502667/28678050-57e464aa-72bd-11e7-92b5-2ea574724397.png)

**Comment by protyposis** [comment]
Which type of video source are you using? Which player version? Where are the subtitles defined/added? Which OS? Subtitles are basically supported in IE11. Would be most effective to supply me a test page, thanks!

**Comment by protyposis** [comment]
This is a bug in the player and not related to the UI. It happens in IE11 when adding subtitles with an URL without a protocol (`//some/url` instead of `http://some/url`).

**Comment by protyposis** [comment]
Will be fixed in the upcoming player 7.3.1.

**Comment by protyposis** [comment]
Fix has been released a while ago, closing.
