### ISSUE TITLE
main.ts file has missing bitmovin.playerui.VolumeSlider and SettingsPanelItem exposed declarations.

### ISSUE THREAD

**Issue by ireneuszsawicki** [bitmovin/bitmovin-player-ui#5]
As in the issue topic, VolumeSlider component is neither not exposed nor imported. Same thing with the SettingsPanelItem.

TimeLabelMode enum is also not accessible as a variable/constant in the bitmovin.playerui namespace.

**Comment by protyposis** [comment]
Fixed in dev branch.

**Comment by ireneuszsawicki** [comment]
Thanks!
