### ISSUE TITLE
getMaxTimeShift value is negative non-zero for Safari HLS live streams

### ISSUE THREAD

**Issue by KennyJJMa** [bitmovin/bitmovin-player-ui#511]
Browser: Safari
OS: Mac OS
Device: Mac
SDK Version: 8.100.0

Related to issue [#335](https://github.com/bitmovin/bitmovin-player-ui/issues/355)
URL: https://bitmovin.com/demos/stream-test?format=hls&manifest={insert your own live stream hls manfiest here}

Steps to reproduce:

1) Open Stream URL with Safari
1) See that `getMaxTimeShift()` return value returns a non-zero negative number (which will trigger the shown visibility on the seekbar) 

* Further investigation will show that `player.getMaxTimeShift()` value from a HLS stream on Safari browser will yield a negative-non-zero float. 
* Ref:  see how the [seekbar component](https://github.com/bitmovin/bitmovin-player-ui/blob/203b041a0433274ece68af4639a3a169239f0716/src/ts/components/seekbar.ts#L386) handles for hiding and showing visibility based on `isLive` and `hasTimeShift` values, and how the player utility functions [detect time shift availability](https://github.com/bitmovin/bitmovin-player-ui/blob/develop/src/ts/playerutils.ts#L107-L117)
* Occasionally, on video resume, the video will infinitely stall because of [DVRWindowExceeded](https://bitmovin.com/docs/player/api-reference/web/web-sdk-v8-api-methods#/player/web/8/docs/enums/core_events.playerevent.html#dvrwindowexceeded) error

Open Stream URL with Chrome
1) Seekbar is invisible
1) See that `getMaxTimeShift()` return value returns zero (which will trigger the hidden visibility on the seekbar) 

* note that `player.getMaxtimeShift()` values from a HLS stream on chrome Browser will yield a value of `0` (zero).

Description
Current behaviour:

when watching a livestream without timeshift the seekbar is visible in the safari browser
ocassionally, when pausing and resuming playback, trying to re-position the safari video playback back to the live edge of the stream, video will infinitely stall
in google chrome the seekbar is invisible (expected behavior)
when pausing and resuming playback, chrome video playback will timeshift corectly to the live edge of the stream

Expected behaviour:
the seekbar is invisible in safari browser and google chrome browser
when pausing and resuming playback in a HLS live stream, playback should timeshift correctly and resume playback correctly

**Comment by jamesdavidholding** [comment]
Hi Kenny,

We will close the ‘Issues’ tab for this Repo this week, and all issues will be closed. If this issue still affects you, please re-raise it through the Bitmovin Support Dashboard, where we will happily pick it up. 

This change improves our responses to you, as the support team is currently not monitoring GitHub repro support sections.

Many thanks,

James - Support
