### ISSUE TITLE
pausedTimeshiftUpdater is not cleared

### ISSUE THREAD

**Issue by OctaFloare** [bitmovin/bitmovin-player-ui#539]
The pausedTimeshiftUpdater is not cleared in the following case:

Player is paused and then the component is unmounted. 

![image](https://user-images.githubusercontent.com/74454053/224757426-b00a11d6-4887-4314-8a42-70e44fee6df1.png)

This issue is causing the following error every 1 second: 
![image](https://user-images.githubusercontent.com/74454053/224757723-44966144-5fcc-4b67-98e3-71827eb12628.png)

**Comment by OctaFloare** [comment]
I also have to mention that this happens for the live player only

**Comment by jamesdavidholding** [comment]
Hi OctaFloare,

We will be closing the ‘Issues’ tab for this Repo this week. If this issue still affects you, please can I ask that you re-raise it through the Bitmovin Support Dashboard, where we will happily pick it up. 

This change improves our response times to you, as the support team is not monitoring GitHub repro.  

Many thanks,

James - Support
