### ISSUE TITLE
Some gulp tasks used in run-sequence didn’t return a stream or promise

### ISSUE THREAD

**Issue by snoopy2199** [bitmovin/bitmovin-player-ui#54]
Hi,
I was wondering that the callback function in gulp task ‘build’ may run before ‘browserify’ and ‘sass’ are finished, because ‘browserify’ and ‘sass’ didn’t [return a stream or promise, or handle the callback](https://www.npmjs.com/package/run-sequence#usage).

Thanks.

**Comment by protyposis** [comment]
I never saw the callback running before the browserify and sass tasks were done, but the missing return values definitely prevented the tasks from running in parallel. Thanks for pointing that out!

**Comment by snoopy2199** [comment]
Thank you :blush:
