### ISSUE TITLE
Accessing UIManager when replacing the built-in UI through location

### ISSUE THREAD

**Issue by ASpwalters** [bitmovin/bitmovin-player-ui#540]
Is there a way to access the UIManager when using the `location` in the configuration to supply the custom built js/css files? I have the need to make use of adding timeline markers dynamically, which appears to exist as a function of uiManager, but I don't know how to access the uiManager instance.

Thanks!

**Comment by stonko1994** [comment]
It should be on `window.playerui.UIManager`.

We also use it like this in our `index.html`:

https://github.com/bitmovin/bitmovin-player-ui/blob/8762349c6d3811fec8afc4e5094c80f322d0fb0e/src/html/index.html#L257

This is defined in the `gulpfile.js` in case you want to modify it:

https://github.com/bitmovin/bitmovin-player-ui/blob/8762349c6d3811fec8afc4e5094c80f322d0fb0e/gulpfile.js#L39-L43

**Comment by dweinber** [comment]
Hey @ASpwalters, did the comment above help you resolve your problem?

**Comment by jamesdavidholding** [comment]
Hi @ASpwalters 

We will be closing the ‘Issues’ tab for this Repo this week. If this issue still affects you, please can I ask that you re-raise it through the Bitmovin Support Dashboard, where we will happily pick it up. 

This change improves our response times to you, as the support team is not monitoring GitHub repro.  

Many thanks,

James - Support
