### ISSUE TITLE
require('bitmovin-player-ui') results in an error

### ISSUE THREAD

**Issue by unki2aut** [bitmovin/bitmovin-player-ui#56]
When using `var playerui = require('bitmovin-player-ui');` this results in the following error:

`Uncaught TypeError: Cannot set property 'playerui' of undefined'`

**Comment by protyposis** [comment]
This error only happens when the UI is loaded before the player, which until now was considered the wrong order. So this is a non-issue.

However, we can easily support both orderings to avoid that in the future.

**Comment by protyposis** [comment]
Implemented in `2.10.0`
