### ISSUE TITLE
seekbar markers overflowing player in some UI configurations

### ISSUE THREAD

**Issue by oberhamsi** [bitmovin/bitmovin-player-ui#568]
at the left and right end of the seekbar the markers don't check if they are overflowing the player. this can lead to the markers being partially invisible.

i removed paddings and the playbacktimelabels in the demo player to show this behavior:

![image](https://github.com/bitmovin/bitmovin-player-ui/assets/53384/126dc2ff-1971-478d-99ec-fc3f00eebd4e)

ideally, if the marker becomes visible it would check it's bounding rect and move left/right if it overflows the player.

**Comment by dweinber** [comment]
@oberhamsi just to be sure we are fully aligned, you're talking about the `seekbarlabel` (where the time and potentially title or thumbnails are displayed in, which shows the `03:20` in your screenshot) and not the `timelinemarker` (the "vertical white lines" on the seekbar in your screenshot), correct?

**Comment by oberhamsi** [comment]
Correct!

**Comment by dweinber** [comment]
Thanks for confirming. Based on that, I'm closing this ticket in favor of #569 as they're duplicates and I think the other ticket outlines the problem quite well.
