### ISSUE TITLE
overlapping issue with seekbar thumbnails

### ISSUE THREAD

**Issue by payamtrack** [bitmovin/bitmovin-player-ui#569]
Hi,

I have increased the size of seekbar thumbnails by using the CSS rules below:
```
.bmpui-ui-seekbar-label {
    width: 30%;
}

.bmpui-ui-seekbar-label .bmpui-seekbar-label-inner > .bmpui-container-wrapper .bmpui-seekbar-thumbnail {
    width: 100% !important;
}
```
However, this causes them to get cut off due to overlapping with the player's edges when hovering over the seek bar up to a specific point at the beginning and end. I am not sure how to address this issue. 

![image](https://github.com/bitmovin/bitmovin-player-ui/assets/135003403/cd4976b9-9f09-4f0f-9fea-9812a9431c74)

As illustrated below, I think the thumbnail container should stop following the mouse pointer when it reaches to the edges, and beyond that point, only the caret-down icon should move with the pointer:

![image](https://github.com/bitmovin/bitmovin-player-ui/assets/135003403/00f52caa-085a-436a-9cdc-297d539ed6fe)

Thanks,

**Comment by jamesdavidholding** [comment]
Hi Payamtrack,

We will be closing the ‘Issues’ tab for this Repo this week. If this issue still affects you, please can I ask that you re-raise it through the Bitmovin Support Dashboard, where we will happily pick it up. 

This change improves our response times to you, as the support team is not monitoring GitHub repro.  

Many thanks,

James - Support
