### ISSUE TITLE
error ReferenceError: self is not defined

### ISSUE THREAD

**Issue by MarlonEngFront** [bitmovin/bitmovin-player-ui#570]
I updated my project to next version 13 and react version 18, after running my project my terminal and my browser printed error = error ReferenceError: self is not defined, before my project ran in version 10 and react version 16.9, I didn't find the solution in many places and nothing helped me. used bitimovim version = "bitmovin-player": "^8.28.0",

**Comment by dweinber** [comment]
Hi,
Is this error coming from the Bitmovin Player or the Bitmovin Player UI? Can you please share steps to reproduce, maybe even a sample project?

In any case, I'd strongly recommend upgrading the player version if `8.28.0` is really what's currently being used (the `^` indicates a higher version could be used but then it comes also down to the `package-lock.json` / `yarn.lock` file in your project), as this version is now more than 3.5 years old. Current is [8.127.0](https://developer.bitmovin.com/playback/docs/release-notes-web#81270).

**Comment by MarlonEngFront** [comment]
the stack trace in my terminal  = - error ReferenceError: self is not defined
    at /xxxx/xxxxx/xxxxxx/node_modules/bitmovin-player/bitmovinplayer.js:11:233
    at Object.<anonymous> (/xxx/xxx/xxxx/node_modules/bitmovin-player/bitmovinplayer.js:12:3)
I updated bitimovim to version = 8.127.0 , and the same error persists.

**Comment by dweinber** [comment]
Thanks @MarlonEngFront. As you can see in the stack trace, the error is coming from the `bitmovinplayer` and not the UI project. As this repo and its issues are only related to the UI project, I'm closing this issue.
Please feel free to reach out to Bitmovin Support via your designated support channel.

**Comment by MarlonEngFront** [comment]
Thanks, I had already seen that, the problem seems that bitmovin tries to access the self reference, but it is not defined, as I updated my project from next 10 to 13 and react from 16 to 18, I will have to change a lot of things to run the project.
