### ISSUE TITLE
<button> should not have superfluous aria attributes

### ISSUE THREAD

**Issue by oberhamsi** [bitmovin/bitmovin-player-ui#606]
`role=button` and `tabIndex=0` are native, built in for <button> and should not be set for every <button>

https://github.com/bitmovin/bitmovin-player-ui/blob/develop/src/ts/components/button.ts#L30

our ARIA review complained about it and referenced

- https://www.w3.org/TR/using-aria/#rule1
- https://www.w3.org/TR/2014/REC-html5-20141028/dom.html#aria-usage-note

**Comment by jamesdavidholding** [comment]
Hi Oberhamsi,

We will be closing the ‘Issues’ tab for this Repo this week. If this issue still affects you, please can I ask that you re-raise it through the Bitmovin Support Dashboard, where we will happily pick it up. 

This change improves our response times to you, as the support team is not monitoring GitHub repro.  

Many thanks,

James - Support
