### ISSUE TITLE
immediately hide UI if mouse leaves uicontainer

### ISSUE THREAD

**Issue by oberhamsi** [bitmovin/bitmovin-player-ui#608]
all big players immediately the UI if the mouse leaves the player area.

it's a trivial change her https://github.com/bitmovin/bitmovin-player-ui/blob/develop/src/ts/components/uicontainer.ts#L174 but i wanted t check first if you think this would need an option or could the default behavior be changed.

i also don't understand the comment about the seek scrub pointer although of course the `if` could stay as is. so the behavior wouldn't change in that situation

**Comment by dweinber** [comment]
I can at least provide insights on the comment:
Assume you are NOT in fullscreen. It can easily happen that the user drags the scrubber but moves the mouse even slightly outside of the UI (e.g. below the video), which would hide the UI, with the seek target time, potentially thumbnail previews, and so on. This means the user doesn't have an idea anymore of where she seeks to.

I don't think we should change the default behavior as this affects all our customers, but I could see that a config option would work nicely in the code that you're referring to.

**Comment by oberhamsi** [comment]
thanks, that makes sense!

i'll do a PR with a config option
