### ISSUE TITLE
google chromecast

### ISSUE THREAD

**Issue by Marhamat92** [bitmovin/bitmovin-player-ui#609]
Hi guys,

Could you please help me with googlecast? I added all components but it still says cast is "unavailable" and doesn't show toggle button to open cast popup.

Thanks,

**Comment by jamesdavidholding** [comment]
Hi Marhamat92

We will be closing the ‘Issues’ tab for this Repo this week. If this issue still affects you, please can I ask that you re-raise it through the Bitmovin Support Dashboard, where we will happily pick it up. 

This change improves our response times to you, as the support team is not monitoring GitHub repro.  

Many thanks,

James - Support
