### ISSUE TITLE
Question about player.EVENT.ON_AD_SKIPPED

### ISSUE THREAD

**Issue by ddhp** [bitmovin/bitmovin-player-ui#85]
Hi there,

I am trying this ui on our product with video ad, 
I found out after I click skip button, the ad does being eliminated, **but `EVENT.ON_AD_SKIPPED` isn't fired**.

I have checked your implementation is simply calling `player.skipAd();`
https://github.com/bitmovin/bitmovin-player-ui/blob/master/src/ts/components/adskipbutton.ts#L75

since bitmovin js player isn't a open source project, I have no way to check if `EVENT.ON_AD_SKIPPED` is dispatched after `player.skipAd()` at some point.

Can you kindly check if this event really being dispatched when `player.skipAd`?

Btw, our product only use bitmovin player to play VAST ad,
so `config.source` is left empty.
just FYI, don't know if this setting would affect the dispatch of `EVENT.ON_AD_SKIPPED`

Thanks!

**Comment by SInCE** [comment]
Hi ddhp, 

How does your player-configuration look like? 
Which advertisement client are you using?

Best regards,
Gernot

**Comment by protyposis** [comment]
Hi! If skipping of the ad is allowed and `player.skipAd()` returns `true` (meaning the skip was allowed and executed), then `ON_AD_SKIPPED` is fired. I validated this in the player code. The `config.source` does not have an impact on the event.

How do you play the ad? Via `config` or `player.scheduleAd`?

**Comment by ddhp** [comment]
Hi, thanks for the quick response.

I setup ad via config, here is it:
```
{
  key: PLAYER_KEY,
  playback: {
    muted: true
  },
  source: {},
  advertising: {
    schedule: {
      'pre-roll-ad': {
        client: 'vast',
        offset: 'pre',
        tag: `https://beta-ssp.tenmax.io/supply/video/rmax-ad?rmaxSpaceId=1aad109e6451459d&domain=kktv.me&referer=encode${pageUrl}`,
      }
    }
  }
};
```

And I tried to expose player instance to global, then
```
// bitmovinp is my project-wise bitmovin module
window.bitmovinp.player.addEventHandler(bitmovinp.player.EVENT.ON_AD_SKIPPED, function() {
  console.log('here')
});
window.bitmovinp.player.skipAd()
```
and true is returned but 'here' isn't logged

Thanks again for your help!

**Comment by protyposis** [comment]
Which player version do you use?

**Comment by protyposis** [comment]
Can you add an `ON_TIME_CHANGED` handler to validate that your handlers are created and working correctly?

**Comment by ddhp** [comment]
Player version v7.5.4
```
Adaptive Video Streaming Service by www.bitmovin.com
bitmovinplayer.js:11 Player Version 7.5.4
```

I modified the script to this:
```
bitmovinp.player.addEventHandler(bitmovinp.player.EVENT.ON_AD_SKIPPED, function() {
  console.log('here')
});
bitmovinp.player.addEventHandler(bitmovinp.player.EVENT.ON_TIME_CHANGED, function() {
  console.log('on time changed')
});
setTimeout(() => {
  bitmovinp.player.skipAd()
}, 4000)

// on time changed keep being logged
```

`ON_TIME_CHANGED` does work

**Comment by ddhp** [comment]
I have found another way to reach what I wanted to do. So I haven't really tested would `ON_SOURCE_UNLOADED` work in this occasion.

Anyway, really appreciate your help!
