### ISSUE TITLE
Where we report are general bitmovin player bugs?   player.getAvailableSegments() api func. very very long response time depend on playlist length

### ISSUE THREAD

**Issue by mesutyigit** [bitmovin/bitmovin-player-ui#89]
var s1 = performance.now()
var a = bitmovin.player('playerLiveTvBitmovin') 
a.getAvailableSegments()
var s2 = performance.now()
console.log("s2-s1 -> " , s2-s1)

Result :>> s2-s1 ->  20509.90000006277

This is very long sync operation and exponential incerease to manifest length. It will be  basic and fast. Why it is very slow calculate for available segments??

**Comment by dweinber** [comment]
Please report general player errors to support@bitmovin.com @mesutyigit.
